services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:25
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse_data:/bitnami/clickhouse

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka_data:/opt/kafka/logs

volumes:
  kafka_data:
    driver: local
